"""empty message

Revision ID: 33ebc71fcf82
Revises: 6e473379048d
Create Date: 2022-05-23 18:37:41.943509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33ebc71fcf82'
down_revision = '6e473379048d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.add_column('planets', sa.Column('name', sa.String(length=120), nullable=True))
    op.alter_column('planets', 'manufacturer',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('model', table_name='planets')
    op.drop_index('model_2', table_name='planets')
    op.create_unique_constraint(None, 'planets', ['name'])
    op.drop_column('planets', 'model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('model', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'planets', type_='unique')
    op.create_index('model_2', 'planets', ['model'], unique=False)
    op.create_index('model', 'planets', ['model'], unique=False)
    op.alter_column('planets', 'manufacturer',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_column('planets', 'name')
    op.alter_column('people', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
